# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5486d44c630bdb393490a9e173bf057adf5a03a6a7abd66eb4bb7d1111605fe8bde6e61c8b21c30e34e91c607c16adad40702cff5a338eedaf2f689a446b68f

test:
  secret_key_base: 518cc0f16555745f67b37f85cc6f6213f47e2a3df39597bf01a76fa2b47a2048984ca5e504ca1c306f7511122b6e6dd004cf260705eaecb0637f540c5d17f351

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
